apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lvp-bind
provisioner: lvp
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: node
    values:
    - ho.me
parameters:
  host_base_path: /pv2/
  fs_type: bind