apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lvp.fullname" . }}
  labels:
    app: lvp
    {{- include "lvp.labels" . | nindent 4 }}
data:
  config.yaml: |
    socket_path: /csi/csi.sock
    database: /db/lvp.redb
    host_prefix: /host/
