---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: lvp
  labels:
    app: lvp
    {{- include "lvp.labels" . | nindent 4 }}
spec:
  attachRequired: true
  podInfoOnMount: false
  fsGroupPolicy: File