apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lvp
provisioner: lvp
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: node
    values:
    - ho.me
parameters:
  host_base_path: /pv2/