image:
  repository: protryon/lvp
resources:
  requests: 
    memory: 16Mi
    cpu: 50m
  limits:
    memory: 256Mi
    cpu: 250m

databaseDir: /var/lib/lvp/
sourcePath: /lvp
kubeletPath: /var/lib/kubelet
enableSanity: false